### ISSUE TITLE
[if] Shortcode Pro v170407.77796-RC

### ISSUE THREAD

**Issue by raamdev** [websharks/if-shortcode-pro#4]
### Downloads

Please see the download links in Slack:
https://websharks.slack.com/archives/C1QMBMXEF/p1491601236374586

### Changelog

v170407.77796-RC

- Adding support for `_no_cache` attribute.
- Adding support for `ua_is_engine="true|false"` attribute.
- Adding support for `ua_is_bot="true|false"` attribute.
- Bumping minimum required WordPress version to v4.6.
- Bumping minimum required version of the WP Sharks Core.
- Adding support for `wp-markdown-extra` filter configuration.
- Removing unnecessary nested shortcode callback handler. Starting with WP 4.6 the new `WP_Hook` class addresses the underlying problem this was solving. See [Issue #1](https://github.com/websharks/if-shortcode-pro/issues/1).
- Enhancing security be removing `basename(__FILE__)` from direct access notices.
- Removing unnecessary lite build variation from `.build.props` file.
- Cleaned up the options page just a bit and corrected some typos.
- Automatically strip leading indents for improved compatibility with Markdown parsers like Jetpack and WP Markdown Extra Pro, etc.

### Reporting Issues / Feedback

Please report any issues or feedback related to this Release Candidate using this GitHub issue. Please post a comment below with details. 

If you are reporting a UI-related issue, please include a screenshot.

If you are reporting a bug, please provide list of steps to reproduce and if the bug is related to an existing GitHub issue, please provide a link to that GitHub issue as well.

---- 

## Reported Issues to Fix

_None at this time._

**Comment by raamdev** [comment]
@renzms Some of the above changes were already tested in https://github.com/websharks/if-shortcode-pro/issues/3. I never got around to publishing that RC and enough time has passed that I'm just doing a new RC that contains those changes you tested + some additional changes Jason has made since then. 

Don't worry about doing a full test of all the changes you already tested in https://github.com/websharks/if-shortcode-pro/issues/3, but please run this through some quick tests and test the additional changes. 

I'll be sure to put out a GA release this time as soon as I get the OK from you. :-)

**Comment by renzms** [comment]
### For Testing:

- [x] Adding support for _no_cache attribute.

**Shortcode:**
>![screen shot 2017-04-13 at 4 02 40 pm](https://cloud.githubusercontent.com/assets/13220018/24995875/06cf85c4-2063-11e7-8d1d-3743424b1f5a.png)

**Front end as logged in user testing cache:**
>![screen shot 2017-04-13 at 4 04 31 pm](https://cloud.githubusercontent.com/assets/13220018/24995880/09055b66-2063-11e7-8656-9c2cc3364496.png)



- [x] Adding support for ua_is_engine="true|false" attribute.

**Tested and verified using: http://www.evolvedwebsites.com.au/googlebot/**

**Shortcode:**
>![screen shot 2017-04-13 at 4 12 47 pm](https://cloud.githubusercontent.com/assets/13220018/24996133/4194148a-2064-11e7-9258-8ef6372e676e.png)


**Front end as logged in user:**
>![screen shot 2017-04-13 at 4 12 57 pm](https://cloud.githubusercontent.com/assets/13220018/24996119/37323422-2064-11e7-89c9-c9e7ad82f741.png)

**Front end view as Googlebot:**
>![screen shot 2017-04-13 at 4 13 15 pm](https://cloud.githubusercontent.com/assets/13220018/24996111/2fd72b60-2064-11e7-8a92-287500978692.png)



- [x] Adding support for ua_is_bot="true|false" attribute.

**Tested and verified using: http://www.evolvedwebsites.com.au/googlebot/**

**Shortcode:**
>![screen shot 2017-04-13 at 4 07 46 pm](https://cloud.githubusercontent.com/assets/13220018/24995994/a60c2c78-2063-11e7-8653-729a2a582bda.png)

**Front end as logged in user:**
>![screen shot 2017-04-13 at 4 08 13 pm](https://cloud.githubusercontent.com/assets/13220018/24995999/aaa4a850-2063-11e7-8754-e085d65f4be4.png)

**Front end view as Googlebot:**
>![screen shot 2017-04-13 at 4 09 14 pm](https://cloud.githubusercontent.com/assets/13220018/24996004/acf9c0b8-2063-11e7-89b5-496c91cdde82.png)


- [x] Cleaned up the options page just a bit and corrected some typos.
- [x] Automatically strip leading indents for improved compatibility with Markdown parsers like Jetpack and WP Markdown Extra Pro, etc.

![screen shot 2017-04-12 at 12 03 23 pm](https://cloud.githubusercontent.com/assets/13220018/24940822/52ae3a94-1f78-11e7-809c-783b4a6d640d.png)
![screen shot 2017-04-12 at 12 03 34 pm](https://cloud.githubusercontent.com/assets/13220018/24940823/540b3c2a-1f78-11e7-91e6-e2e7bf3e90d4.png)



Previously Tested and confirmed working in #3 

- [x] Enhancing security be removing basename(__FILE__) from direct access notices.
- [x] Bumping minimum required version of the WP Sharks Core.
- [x] Adding support for wp-markdown-extra filter configuration.
- [x] Removing unnecessary nested shortcode callback handler. Starting with WP 4.6 the new WP_Hook class addresses the underlying problem this was solving. See Issue #1.
- [x] Removing unnecessary lite build variation from .build.props file.
- [x] Bumping minimum required WordPress version to v4.6.

**Comment by renzms** [comment]
@raamdev 

### Confirmed Working

All tests complete :) 👍

**Comment by raamdev** [comment]
Thanks Renz!

----

[if] Shortcode Pro v170413.74328 has been released: https://wpsharks.com/product/if-shortcode-pro/changelog
