### ISSUE TITLE
Link to plugin broken

### ISSUE THREAD

**Issue by Gibsonion** [websharks/if-shortcode-pro#5]
## EXPLANATION OF THE ISSUE

Link in the footer description of the main page of this project is broken, goes to 404 page https://github.com/websharks/if-shortcode-pro/blob/dev/wpsharks.com

## STEPS TO REPRODUCE THE ISSUE

Click on the link in the footer 

## BEHAVIOR THAT I EXPECTED

Should go to here https://wpsharks.com/product/if-shortcode-pro.

Update: I have submitted a fix.

**Comment by raamdev** [comment]
@Gibsonion Thanks for the report!

> Update: I have submitted a fix.

Where did you submit that fix? I don't see a Pull Request...

**Comment by Gibsonion** [comment]
Ah sorry seems I selected the wrong option when submitting the fix, I've redone it, hopefully that's worked now.

**Comment by raamdev** [comment]
Merged! Thanks for the PR.
